### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by antonypope** [experiandataquality/GlobalIntuitive#10]
Currently when a service error is returned it appears to continue trying indefinitely.
Option to enter manually or return a customer specific error message

**Comment by jbate** [comment]
In addition to 401 errors, 400, 403, 404 and timeouts are handled better now.
Integrators can also subscribe to events to apply behaviour or display custom messages.

500 Internal Server Errors aren't handled yet as this couldn't be tested.
