### ISSUE TITLE
Country and language specific Global 7-Line labels.

### ISSUE THREAD

**Issue by antonypope** [experiandataquality/GlobalIntuitive#11]
Global Default: Address Line 1; Address Line 2; Address Line 3; Locality; Province; Postal/ZIP Code; Country.
Ability to change labels based on country e.g. ZIP code for USA and Post Code for UK.
Ability to change labels based on language e.g. French and English for Canada.

**Comment by niick2112** [comment]
User friendly labels when editing address manually done.

Reference to pull request: 0f4a8612e9651fc08a050a67c09ccaeb8a9f9794

**Comment by jbate** [comment]
Shouldn't the relevant labels be returned by the API? Hence abstracting this requirement away from the integrator?

**Comment by jbate** [comment]
Translations for the address lines can however now be specified. By language and country.
See commit: 457df838ff49226b068ce73e80366532bf04ef96
