### ISSUE TITLE
Keyboard obscures suggestion list on mobile devices

### ISSUE THREAD

**Issue by almills** [experiandataquality/GlobalIntuitive#4]
When using on a phone, the banner takes us considerable room and the suggestion list appears at least partly obscured by the on screen keyboard

**Comment by marak210** [comment]
We should decrease the banner width considerably even though it's just for demo purposes.

**Comment by jbate** [comment]
The height of the banner and size of the heading have now been greatly reduced.
This now makes it a lot easier to see the picklist as you type an address.

See commit: d7b62b6b685de8e73c7ddb357be06436217bf66d
