### ISSUE TITLE
Internal labels displayed to user

### ISSUE THREAD

**Issue by almills** [experiandataquality/GlobalIntuitive#5]
On the edit my address screen, the form labels are the internal json labels. We should have user friendly labels instead.

**Comment by andyflatwhite** [comment]
Should the internal json lables provide default user friendly UI text?

**Comment by antonypope** [comment]
Also covered by #11 and #12

**Comment by jbate** [comment]
Closing issue as #11 and #12 both cover this more specifically, as mentioned by @antonypope
